services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes services
  stats_tables_cleaner.service:
    class: D3nysm\Bundle\StatsTablesCleaner\Service\StatsTablesCleanerService

  stats_tables_cleaner.command:
    class: D3nysm\Bundle\StatsTablesCleaner\Command\CleanCommand
    arguments:
      - '@stats_tables_cleaner.service'
